name: Step 5, Link PR to Issue

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Get current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          if [ -f .github/steps/-step.txt ]; then
            echo "current_step=$(cat .github/steps/-step.txt)" >> $GITHUB_OUTPUT
          else
            echo "current_step=0" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  advance_if_linked_and_merged:
    name: PR was merged and links to issue
    needs: get_current_step
    if: >-
      ${{
        github.event.pull_request.merged == true &&
        needs.get_current_step.outputs.current_step == '5' &&
        contains(github.event.pull_request.body, 'closes #')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Update to step 6
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: 6
          branch_name: update-game

  advance_if_finished_comment:
    name: Fallback – learner typed "finished"
    needs: get_current_step
    if: >-
      ${{
        github.event_name == 'issue_comment' &&
        needs.get_current_step.outputs.current_step == '5' &&
        contains(github.event.comment.body, 'finished')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Update to step 6
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: 6
          branch_name: update-game

